name: CI - Jeu de Traduction

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write  


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Étape Build (simulée)
        run: echo " Simulation de la compilation... (rien à compiler pour HTML)"

      - name: Vérifier que index.html est présent
        run: test -f public/index.html && echo "Le fichier index.html est présent." || (echo " Fichier manquant !" && exit 1)

      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . 

      - name: Création de tag Git
        if: github.ref == 'refs/heads/master'
        run: |
          TAG="v1.0.${{ github.run_number }}"
          git tag $TAG
          git push origin $TAG
          echo "Tag $TAG créé et poussé !"
