name: CI - Jeu de Traduction

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write  
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du code
      - name: Checkout du code
        uses: actions/checkout@v4

      # Étape 2: Vérifier le statut Git
      - name: Vérifier le statut Git
        run: |
          git status
          git log --oneline -n 5

      # Étape 3: Configurer Git
      - name: Configurer Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Étape 4: Étape Build (simulée)
      - name: Étape Build (simulée)
        run: echo "Simulation de la compilation... (rien à compiler pour HTML)"

      # Étape 5: Vérifier que index.html est présent
      - name: Vérifier que index.html est présent
        run: test -f public/index.html && echo "Le fichier index.html est présent." || (echo "Fichier manquant !" && exit 1)

      # Étape 6: Création de tag Git
      - name: Création de tag Git
        if: github.ref == 'refs/heads/master'
        run: |
          git status
          TAG="v1.0.${{ github.run_number }}"
          git tag $TAG
          git push origin $TAG
          echo "Tag $TAG créé et poussé !"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy  # On doit etre sur que cette étape est bien avnt le déploiment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'  

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
