name: CI - Jeu de Traduction

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du code
      - name: Checkout du code
        uses: actions/checkout@v4

      # Étape 2: Vérifier le statut Git
      - name: Vérifier le statut Git
        run: |
          git status
          git log --oneline -n 5

      # Étape 3: Configurer Git
      - name: Configurer Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Étape 4: Étape Build (simulée)
      - name: Étape Build (simulée)
        run: echo "Simulation de la compilation... (rien à compiler pour HTML)"

      # Étape 5: Vérifier que index.html est présent
      - name: Vérifier que index.html est présent
        run: test -f public/index.html && echo "Le fichier index.html est présent." || (echo "Fichier manquant !" && exit 1)
   
    # Étape 6: Création de tag Git
      - name: Création de tag Git
        if: github.ref == 'refs/heads/master'
        run: |
          git status
          TAG="v1.0.${{ github.run_number }}"
          git tag $TAG
          git push origin $TAG
          echo "Tag $TAG créé et poussé !"


      # Étape 7: Déploiement sur GitHub Pages
      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages 
          allow_empty_commit: false  
          force_orphan: true  
          disable_nojekyll: true 

      